modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/cocona20xx/preset-dimension-folders/issues"
license = "MPL2.0"

[[mods]]
modId = "preset_dims"
version = "${version}"
displayName = "Preset Dimensions"
authors = "rin/cocona20xx (trinitysoft)"
description = '''
Extremely bare-bones mod for copying preset dimension folders into a given world's /dimensions folder.
'''
logoFile = "assets/preset_dims/icon.png"

[[dependencies.preset_dims]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.preset_dims]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"